workspace:
  base: /go/src/github.com/Oppodelldog/droxy
  path: /

pipeline:
  build:
    group: build
    image: oppodelldog/droxy:latest
    pull: true
    commands:
      - make ci
      
  functional-tests:
    group: build
    image: oppodelldog/docker-bats:latest
    pull: true
    commands:
        - make functional-tests