workspace:
  base: /go
  path: src/docker-proxy-command

pipeline:
  build:
    image: golang:1.9.4
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go get ./...
      - go test -v ./...
      - go build
matrix:
 GO_VERSION:
   - latest
   - "1.9"