# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/drone/envsubst"
  source = "https://github.com/Oppodelldog/envsubst.git"
  revision = "73c8b7a36b56dac63beeadd05206aab260d06d70"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/inconshreveable/mousetrap" # dependency for cobra in windows, dep did not resolve on linux
  revision = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"

[[constraint]]
  name = "github.com/Oppodelldog/filediscovery"
  version = "0.1.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.13.1"
  
[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.2"
