Version="1"
Logging=true
    [[command]]
      name = "build-container"
      image = "oppodelldog/droxy:functional-tests"
      isTemplate = true
      removeContainer=true

    # test simple output
    [[command]]
    	name = "outputs_test123"
        template = "build-container"
    	entryPoint = "echo"
    	command="test123"
    	
    # test impersonation
    [[command]]
    	name = "full-feature"
        template = "build-container"
    	entryPoint = "sh"
    	
        impersonate=true
        isinteractive=true
        volumes = ["${DROXY_MOUNT_DIR}:/test-dir"]
        workDir = "${DROXY_HOST_TEST_DIR}"
        AutoMountWorkDir=true
        envvars = ["TESTVAR=${DROXY_TEST_VAR}"]
