Version="1"
Logging=true
    [[command]]
      name = "build-container"
      image = "docker-bats"
      isTemplate = true
      removeContainer=true

    # test simple output
    [[command]]
    	name = "outputs_test123"
        template = "build-container"
    	entryPoint = "echo"
    	command="test123"
