Version="1"

    [[command]]
      name = "basic go command"
      image = "oppodelldog/droxy:latest"
      isTemplate = true
      addGroups = true
      impersonate = true
      workDir = "${PWD}"
      removeContainer=true
      isInteractive=true
      volumes = [
          "${GOPATH}:${GOPATH}",
          "${HOME}:${HOME}",
          "/etc/passwd:/etc/passwd:ro",
          "/etc/group:/etc/group:ro",
      ]

      envvars = [
          "GOPATH=${GOPATH}",
      ]

    [[command]]
    	name = "make"
        template = "basic go command"
    	entryPoint = "make"

    [[command]]
    	name = "debugcontainer"
        template = "basic go command"
    	entryPoint = "bash"