Version="1"

    [[command]]
      name = "build-container"
      image = "oppodelldog/droxy:latest"
      #image = "droxytest"
      isTemplate = true
      addGroups = true
      impersonate = true
      removeContainer=true
      isInteractive=true
      volumes = [
          "/tmp:/tmp",
          "${PWD}:/go/src/github.com/Oppodelldog/droxy",
          "/etc/passwd:/etc/passwd:ro",
          "/etc/group:/etc/group:ro",
          "${GOPATH}/pkg:/go/pkg",
          "${GOPATH}/mod:/go/mod",
          "${HOME}/.cache/golangci-lint:${HOME}/.cache/golangci-lint"
      ]
      envvars = [
          "GOCACHE=/tmp"
      ]

    [[command]]
    	name = "make"
        template = "build-container"
    	entryPoint = "make"

    [[command]]
    	name = "debugcontainer"
        template = "build-container"
    	entryPoint = "bash"